---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-blocker-etc-pvc
  namespace: pi-hole
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-blocker-dns-pvc
  namespace: pi-hole
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
