apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi-hole-regx-install
  namespace: pi-hole
spec:
  schedule: "1 0 1 12 *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: pi-hole-blocker-sa
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 0
          containers:
          - name: pi-hole-regx-install
            image: ablancom/pi-hole-installregx
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "100Mi"
                cpu: "50m"
              limits:
                memory: "200Mi"
                cpu: "100m"
            command:
              - /bin/bash
              - -c
              - |
                  cd /etc/pihole
                  curl -X GET https://raw.githubusercontent.com/ablancoze/piHole-kubernetes/main/installregexp.py >> installregexp.py
                  sleep infinity
            volumeMounts:
            - name: pihole-etc
              mountPath: /etc/pihole/  
            - name: pihole-dns
              mountPath: /etc/dnsmasq.d/
          volumes:
          - name: pihole-etc
            persistentVolumeClaim:
              claimName: pi-hole-blocker-etc-pvc
          - name: pihole-dns
            persistentVolumeClaim:
              claimName: pi-hole-blocker-dns-pvc

